In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
rng = np.random.default_rng(seed=42)

How likely is it that you roll doubles when rolling two dice?



In [14]:
nrows = 1_000

In [197]:
dice1 = rng.integers(1,6, 10_000)
dice1[:5]

array([4, 4, 4, 2, 4])

In [201]:
dice1 == 1

array([False, False, False, ..., False, False, False])

In [203]:
(dice1 == 1).sum()

1972

In [205]:
likely_roll = (dice1 == 1).sum()/ len(dice1)
likely_roll

0.1972

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?



In [24]:
flips = rng.choice([0,1],(1_000,8))
flips[:3]

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 0]])

In [26]:
flips_sum = flips.sum(axis=1)
flips_sum[:3]

array([4, 5, 3])

In [206]:
exact_three = (flips_sum ==3).sum()
exact_three

221

In [213]:
prob_three_head = (flips_sum ==3).sum()/1_000
prob_three_head

0.221

What is the probability of getting more than 3 heads?

In [214]:
flips_more = rng.choice([0,1], (1_000,4))
flips_more[:4]

array([[1, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [215]:
flips_more = flips_more.sum(axis = 1)
flips_more[:4]

array([2, 1, 2, 4])

In [216]:
more_than_three = (flips_more == 4).sum()
more_than_three

65

In [218]:
more_head_prob = (flips_more == 4).sum() / 1_000
more_head_prob

0.065

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?



In [81]:
d_s = 1/4
d_s

0.25

In [90]:
billboards = rng.random((1_000,2))


In [91]:
billboards <= .25

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [92]:
(billboards <= .25) .sum(axis=1)

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 2, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 2, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 2,
       0, 0, 0, 0, 1, 0, 1, 2, 0, 1, 1, 0, 2, 0, 1, 2, 0, 0, 1, 0, 0, 0,
       2, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 2,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       2, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 2, 0, 2, 1, 0,
       1, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0,
       0, 1, 2, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 2, 1, 1, 0, 2, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 2, 0, 0, 1, 0,

In [93]:
twice_ds = (billboards <= .25).sum()
twice_dsc

542

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [111]:
poptarts = np.random.normal(3, 1.5, (1_000,5))
poptarts = poptarts

In [112]:
pop_friday = poptarts.sum(axis=1)
pop_friday

array([19.23206663, 16.17494019, 10.38200593,  8.45746546,  7.65494123,
       14.52881996, 15.39521853, 14.44056778, 11.92424601, 18.14399956,
       17.5385686 ,  8.58816736, 18.25458727, 15.96414406, 17.14310723,
       10.25603633, 14.90724527, 13.82598669, 15.06784001, 13.54581286,
       16.75182415, 16.39382143, 20.81943205, 16.95030024, 14.93476557,
       16.91578782, 12.11690609, 14.45630061, 17.38032622, 12.64614121,
       11.0157502 , 20.39331725, 16.52550113, 19.22361701, 19.68497113,
       12.90921785, 14.80157169, 14.85065852, 17.74028712, 21.58575406,
       12.04542007, 12.57531037, 11.84065039, 16.2465348 , 13.97690057,
       20.97125934, 12.74630689, 17.9747382 , 12.22324404, 12.87733505,
       16.68123693, 15.29908576, 12.56023609, 13.71480659, 17.35341179,
        9.32766527, 17.19926361, 13.48923215, 17.44719386, 22.95510175,
       16.61587467, 11.97568282, 12.56970291, 11.93515096,  6.85776988,
       19.5941609 , 20.26355419, 16.1629875 , 14.11098699, 20.86

In [113]:
pop_friday <= 16

array([False, False,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
        True,  True, False, False, False, False,  True, False,  True,
        True, False,  True,  True, False, False, False, False,  True,
        True,  True, False, False,  True,  True,  True, False,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
       False,  True, False,  True, False, False, False,  True,  True,
        True,  True, False, False, False,  True, False, False, False,
        True,  True,  True, False, False, False,  True,  True,  True,
        True, False, False,  True,  True, False, False, False, False,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True, False, False, False, False, False,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
       False,  True,  True, False,  True, False,  True,  True, False,
        True,  True,

In [115]:
pop_f = (pop_friday <= 16).mean()
pop_f

0.613

5. Compare Heights

. Men have an average height of 178 cm and standard deviation of 8cm.

. Women have a mean of 170, sd = 6cm.

. Since you have means and standard deviations, you can use np.random.normal to generate observations.

. If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?


In [122]:
men_height = np.random.normal(178, 8, 1_000)
women_height = np.random.normal(170, 6, 1_000)

In [123]:
women_height  > men_height

array([False, False, False,  True,  True, False, False,  True, False,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False,  True,  True,
       False,  True, False, False,  True, False, False, False, False,
        True,  True, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True,  True,  True,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False,  True,  True,  True,
       False, False, False, False,  True,  True, False, False, False,
       False, False,

In [126]:
choosen_women = (women_height  > men_height).mean()
choosen_women

0.224

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

In [127]:
install_fail = 1/250
install_fail

0.004

In [131]:
first_fifty = np.random.random((1_000, 50))
first_100 = np.random.random((1_000, 100))
first_150 = np.random.random((1_000, 150))
first_450 = np.random.random((1_000, 450))

In [142]:
first_fifty > install_fail

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [143]:
no_issue = (first_fifty > install_fail).mean(axis=1)
no_issue

array([1.  , 1.  , 1.  , 1.  , 1.  , 0.98, 0.98, 1.  , 0.98, 1.  , 0.98,
       1.  , 1.  , 1.  , 0.98, 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 0.98, 1.  , 1.  , 1.  , 0.98, 1.  , 1.  , 1.  , 0.98,
       0.98, 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.98, 0.98,
       1.  , 0.98, 1.  , 1.  , 0.98, 1.  , 1.  , 0.98, 0.98, 1.  , 1.  ,
       1.  , 1.  , 1.  , 1.  , 1.  , 0.98, 1.  , 1.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 1.  , 0.98, 1.  , 1.  , 1.  , 0.98, 1.  , 1.  ,
       0.98, 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.98, 1.  , 1.  , 1.  ,
       1.  , 1.  , 0.98, 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.98, 1.  ,
       1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.98, 1.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 0.98, 1.  , 1.  , 0.98, 0.98, 1.  , 1.  , 1.  , 0.98,
       1.  , 1.  , 1.  , 1.  , 1.  , 0.98, 1.  , 0.

In [146]:
no_issue.sum()/len(no_issue)

0.99626

In [148]:
first_100 > install_fail

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [149]:
still_no_issue = (first_100 > install_fail).mean()
still_no_issue

0.99632

In [157]:
first_150 < install_fail

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [160]:
first_issue = (first_150 < install_fail).sum(axis=1)
first_issue

array([2, 1, 0, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 1, 3, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 3, 1, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 2, 2, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 2, 2, 2, 2, 0, 1, 1, 0,
       2, 0, 0, 1, 0, 2, 1, 2, 0, 0, 0, 0, 0, 1, 2, 3, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 2, 0, 0, 0, 1, 0, 2, 1, 0, 2, 1, 1, 0, 2, 0, 2, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 2, 1, 0, 1, 0, 2, 1, 1, 1,
       1, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0,
       1, 1, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 2, 0, 3, 0, 1, 0, 0, 0, 0, 1, 1,

In [161]:
first_issue > 0


array([ True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False, False,  True,  True,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True,  True,  True, False, False, False,  True,
       False, False,  True, False,  True, False,  True, False, False,
       False, False, False, False,  True,  True, False,  True,  True,
        True, False, False, False, False, False,  True,  True, False,
       False, False, False,  True, False, False,  True, False, False,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True, False,  True, False, False, False, False,
        True,  True, False, False,  True, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True, False, False, False,  True,  True,
        True,  True,

In [168]:
first_450 = (np.random.random((10000, 450)) > fail).prod(axis=1).mean()
first_450

0.1603

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [186]:
three_days = rng.random((1_000, 3))
three_days[:3]

array([[0.7287073 , 0.00118248, 0.96283469],
       [0.18602721, 0.26341032, 0.25903774],
       [0.27998277, 0.18487996, 0.02194494]])

In [187]:
three_days > 0.7

array([[ True, False,  True],
       [False, False, False],
       [False, False, False],
       ...,
       [False, False, False],
       [False,  True,  True],
       [False, False,  True]])

In [188]:
seen_days = (three_days > 0.7).sum(axis=1)
seen_days[:3]

array([2, 0, 0])

In [189]:
seen_days != 0

array([ True, False, False,  True,  True, False,  True,  True, False,
        True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True, False, False,  True,  True, False,  True, False,
        True, False,  True,  True,  True,  True,  True,  True, False,
       False,  True, False, False, False,  True,  True,  True,  True,
       False,  True,  True, False, False,  True,  True, False,  True,
        True, False, False, False,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True, False, False,  True,  True, False,
        True,  True, False, False,  True, False, False,  True, False,
        True,  True,  True, False,  True, False,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,

In [190]:
might_see = (seen_days != 0).sum()
might_see

666

In [191]:
might_see / len(seen_days)

0.666

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?



In [193]:
birthday_23 = pd.DataFrame(np.random.randint(0,365,(10_000,23)))
share_birthday_23 = birthday_23.apply(lambda x: len(set(x)) != len(x),axis=1).mean()
share_birthday_23
birthday_20 = pd.DataFrame(np.random.randint(0,365,(10_000,20)))
share_birthday_20 = birthday_20.apply(lambda x: len(set(x)) != len(x),axis=1).mean()
share_birthday_20
birthday_40 = pd.DataFrame(np.random.randint(0,365,(10_000,40)))
share_birthday_40 = birthday_40.apply(lambda x: len(set(x)) != len(x),axis=1).mean()
share_birthday_40


0.8923

In [196]:
import numpy as np

num_simulations = 1000

# For 23 people
birthdays_23 = np.random.randint(0, 365, size=(num_simulations, 23))
share_birthday_23 = np.mean([len(set(people)) != len(people) for people in birthdays_23])
print("Probability of two people sharing a birthday in a room of 23 people:", share_birthday_23)

# For 20 people
birthdays_20 = np.random.randint(0, 365, size=(num_simulations, 20))
share_birthday_20 = np.mean([len(set(people)) != len(people) for people in birthdays_20])
print("Probability of two people sharing a birthday in a room of 20 people:", share_birthday_20)

# For 40 people
birthdays_40 = np.random.randint(0, 365, size=(num_simulations, 40))
share_birthday_40 = np.mean([len(set(people)) != len(people) for people in birthdays_40])
print("Probability of two people sharing a birthday in a room of 40 people:", share_birthday_40)


Probability of two people sharing a birthday in a room of 23 people: 0.481
Probability of two people sharing a birthday in a room of 20 people: 0.405
Probability of two people sharing a birthday in a room of 40 people: 0.892
